<?php


namespace Djc\Phalcon\Models;


class ModelSequence extends BaseModel
{

    public $tableName;
    public $highModSequence;

    protected $_modifiers = false;
    protected $_softDeletes = false;
    protected $_timeStamps = false;

    public function initialize()
    {
        $this->setSource('modelSequence');
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}